### ISSUE TITLE
discord disabled my account

### ISSUE THREAD

**Issue by SharkFinPro** [LegitSoulja/JDE#1]
well, the title says it all. Ill let you know when its reenabled. If you need me, my email is sharkfinpro@hotmail.com

**Comment by LegitSoulja** [comment]
@SharkFinPro how? lol ok then.

**Comment by SharkFinPro** [comment]
@LegitSoulja i made a new alt. add it: shrekopro#5488

**Comment by LegitSoulja** [comment]
@SharkFinPro added
